### ISSUE TITLE
[Sugestão] Criar politica de branchs e PRs

### ISSUE THREAD

**Issue by l-ricardo** [Interacao-Humano-Computador/2023.2-Dominio-Publico#14]
Documentar como será a politica de branchs conforme discutimos em reunião.
- Para adicionar coisas: Primeiro  cria nova Branch a partir da main, faz alterações e cria PR.
- Para nomear branchs: Nome sem caracteres especiais, acentuação inclusa "ç^~´"
- Depois do PR revisado e mergeado: Deletar branch

**Comment by ViictorHugoo** [comment]
- Nomes significativos
