### ISSUE TITLE
Video de avaliação de usabilidade do site escolhido está com restrito

### ISSUE THREAD

**Issue by l-ricardo** [Interacao-Humano-Computador/2023.2-Dominio-Publico#49]
# Descrição
Como no titulo

# Imagem 
![image](https://github.com/Interacao-Humano-Computador/2023.2-Dominio-Publico/assets/88405145/002525be-4b53-47f0-b984-0abfe9c6b533)

# Solução Proposta
Colocar video no youtube junto com as gravacoes de entregas e substituir por um iframe

**Comment by Maliz30** [comment]
Alterações feitas e esperando aprovação no PR #54
